{{- if .Values.db.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "AppCtx.dbName" . }}
  labels: {{ include "AppCtx.dbLabels" . | nindent 4 }}
data:
  db_name: {{ .Values.db.name }}
  db_path: "/var/lib/postgresql/data/pgdata"
{{- end }}