{{- if .Values.db.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "AppCtx.dbName" . }}-credentials
  labels: {{ include "AppCtx.dbLabels" . | nindent 4 }}
type: Opaque
data:
  pg_username: YWRtaW4=   # user: admin
  pg_password: dGVzdDEyMyo=  # pwd: test123*
{{- end }}