{{- if .Values.db.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "AppCtx.dbName" . }}
  labels: {{ include "AppCtx.dbLabels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.db.pvc.size }}
  storageClassName: {{ .Values.db.pvc.storageClass }}
{{- end }}
